### ISSUE TITLE
make sigpyproc package

### ISSUE THREAD

**Issue by gijzelaerr** [AA-ALERT/spack#6]
https://github.com/ewanbarr/sigpyproc.git

**Comment by gijzelaerr** [comment]
done 130c464138b8bedc9fcfcfa07d5a95116dc1b7e3

**Comment by loostrum** [comment]
The python bindings are there, but it also produces a few shared libs that are needed but cannot be found. They are present in the sigpyproc install dir though (e.g. libSigPyProc.so). It seems `spack activate` only takes care of the python part. 
Running `spack load sigpyproc` does not fix this, presumably because the libraries are not installed to `install_dir/lib` but to `install_dir/lib/python2.7/site-packages`

**Comment by gijzelaerr** [comment]
so you are saying the python module doesn't work since the shared libraries are not in `LD_LIBRARY_PATH`? not sure if that is required...

this is currently installed:
```
./lib/python2.7/site-packages/libSigPyProcTim.so
./lib/python2.7/site-packages/libSigPyProc8.so
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info/not-zip-safe
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info/SOURCES.txt
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info/dependency_links.txt
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info/top_level.txt
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info/requires.txt
./lib/python2.7/site-packages/sigpyproc-0.1.1-py2.7.egg-info/PKG-INFO
./lib/python2.7/site-packages/libSigPyProc.so
./lib/python2.7/site-packages/libSigPyProcSpec.so
./lib/python2.7/site-packages/sigpyproc
./lib/python2.7/site-packages/sigpyproc/TimeSeries.py
./lib/python2.7/site-packages/sigpyproc/__init__.py
./lib/python2.7/site-packages/sigpyproc/Filterbank.pyc
./lib/python2.7/site-packages/sigpyproc/Readers.pyc
./lib/python2.7/site-packages/sigpyproc/Header.py
./lib/python2.7/site-packages/sigpyproc/FoldedData.py
./lib/python2.7/site-packages/sigpyproc/Readers.py
./lib/python2.7/site-packages/sigpyproc/FourierSeries.pyc
./lib/python2.7/site-packages/sigpyproc/Utils.pyc
./lib/python2.7/site-packages/sigpyproc/__init__.pyc
./lib/python2.7/site-packages/sigpyproc/Utils.py
./lib/python2.7/site-packages/sigpyproc/FourierSeries.py
./lib/python2.7/site-packages/sigpyproc/HeaderParams.pyc
./lib/python2.7/site-packages/sigpyproc/Filterbank.py
./lib/python2.7/site-packages/sigpyproc/ctype_helper.pyc
./lib/python2.7/site-packages/sigpyproc/TimeSeries.pyc
./lib/python2.7/site-packages/sigpyproc/ctype_helper.py
./lib/python2.7/site-packages/sigpyproc/HeaderParams.py
./lib/python2.7/site-packages/sigpyproc/FoldedData.pyc
./lib/python2.7/site-packages/sigpyproc/Header.pyc
./lib/python2.7/site-packages/libSigPyProc32.so
```

so everything is there? but the shared libraries are not found? Can you try setting `LD_LIBRARY_PATH` to the `site-packages` folder. otherwise can you give a command and error that illustrates the problem.

**Comment by loostrum** [comment]
Yep that is the issue. The required libraries are in the list you post, but python modules are activated using `spack activate`. This symlinks the sigpyproc folder in site-packages to site-packages in the python install folder, but not the shared libs. Indeed adding the sigpyproc site-packages folder to `LD_LIBRARY_PATH` fixes this.

I can look up a command later, but that does need a filterbank file as it only fails once trying to read one.

**Comment by gijzelaerr** [comment]
ok so copying those shared libraries to prefix.lib should work.

**Comment by loostrum** [comment]
Doesn't seem to be an issue anymore; sigpyproc can find its shared libs now without manually changing `LD_LIBRARY_PATH`.
